### ISSUE TITLE
🔥🔥🔥 api.chatie.io服务异常，HTTP错误码503

### ISSUE THREAD

**Issue by su-chang** [Chatie/server#97]
偶尔可以访问到，但是online的数量变动较大，可能是有啥token触发了统计的bug，导致服务异常。

> OMG!!! Chatie AppOnline: 9513 Status

**极端案例截图**
![01b8eb5f-4135-46c0-a30f-ae8c2022f83f](https://user-images.githubusercontent.com/9332609/217321047-f455a577-f5a9-4701-8db8-ce713f86fd41.jpeg)

**响应异常截图**
![image](https://user-images.githubusercontent.com/9332609/217321425-1b919a4d-bcc5-4d8a-b8e2-7ab219453f46.png)

**Comment by huan** [comment]
According to the restart log of the server, the token started with `puppet_workpro_5491f2c629034292b7ab85fc45`**** keeps registering itself hundreds of times.

Could you check it a little bit? There are also some tokens that have this issue too.

**Comment by su-chang** [comment]
Thanks for your logs, I will check it now.

**Comment by su-chang** [comment]
已恢复，是由于Timer没有被正确清理掉导致的反复向api.chatie.io注册导致的bug。
